### ISSUE TITLE
Localization Issue/ Error

### ISSUE THREAD

**Issue by rfolan** [episerver/AlloyDemoKit#11]
When I run the Alloy Demo Kit I am getting the following error.  It appears to be an issue with the localization services not being able to find the resource  key?  Not quite sure, but I can sometime get past this with an IIS Reset.

Error:
Collection was modified; enumeration operation may not execute.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

Source Error: 

Line 44:             string value;
Line 45: 
Line 46:             if(!LocalizationService.Service.TryGetString(resurceKey, out value))
Line 47:             {
Line 48:                 value = resurceKey;

**Comment by egandalf** [comment]
I've seen this as well. I think it's a threading issue. What I did was move everything (manually) back into XML files and remove the DB provider from the project.

It seems to only happen on VMs or other small machine instances.

**Comment by egandalf** [comment]
Here's the file Brad McDavid modified to fix the problem in his installation: https://gist.github.com/bmcdavid/79caec34d36a0d763df2b3e69d9a2a85

**Comment by egandalf** [comment]
Full conversation in Valdis' project: https://github.com/valdisiljuconoks/LocalizationProvider/issues/41

**Comment by vnbaaij** [comment]
Solved with Episerver and Localization module updates
