### ISSUE TITLE
Not able to add criteria to visitor group

### ISSUE THREAD

**Issue by cjsharp1** [episerver/AlloyDemoKit#13]
The new "VisitorGroupUIStyling" pieces are breaking visitor group UI. I am unable to drop the criteria when building a new visitor group.

Tested in latest Chrome.

**Comment by davidknipe** [comment]
Hi Chris I can recreate on localhost. Strangely when running on a server all works well. Will investigate further.

**Comment by vnbaaij** [comment]
Don't think this is an issue anymore
