### ISSUE TITLE
database read-only error

### ISSUE THREAD

**Issue by javafun** [episerver/AlloyDemoKit#16]
I pulled down the latest master and ran into the following error

Failed to update database "alloydemokit" because the database is read-only.

Can anyone help with this issue?

**Comment by vnbaaij** [comment]
Did you already have an installation of the demokit? It seem so as the warning says it failed to update.

If yes, then make sure you stop the localdb instance before downloading the latest version. You can stop the instance with the following command (either from a command prompt or a PowerShell): 'sqllocaldb stop'

**Comment by javafun** [comment]
Yes, I had local copy of the AlloyDemoKit repo for client demo. It used to be working fine. When there are updates, I just reset all my local changes and pull down the latest one. 

I opened the localdb from SSMS and found the database is showing as read-only, never thought the localdb had this feature before.  Simple fix is to set read-only back to false, problem fixed.

**Comment by vnbaaij** [comment]
Glad it is solved
