### ISSUE TITLE
Database version issue

### ISSUE THREAD

**Issue by sinanaltaii** [episerver/AlloyDemoKit#21]
The database 'alloydemokit' cannot be opened because it is version 869. This server supports version 852 and earlier. A downgrade path is not supported.
Could not open new database 'alloydemokit'. CREATE DATABASE is aborted.
Is it possible to solve this? may make the database compatible with older sql server?
That would be really nice

**Comment by vnbaaij** [comment]
Hi,

Unfortunately we cannot make the database compatible with older SQL Server version. The one supported is SQL LocalDB 2017
