### ISSUE TITLE
Null reference exception running fresh clone of solution

### ISSUE THREAD

**Issue by JiriCepelkaFirstLineSoftware** [episerver/AlloyDemoKit#23]
Today (8th of February) I downloaded _Episerver AlloyDemoKit_. When I tried to run it using _IIS Express_ I got **null reference exception**. 

**[Exception page](http://uzivatel919.sweb.cz/Page.html)**, **[General event info](http://uzivatel919.sweb.cz/Event%20General%20Info.txt)** and **[event XML](http://uzivatel919.sweb.cz/Event.xml)** are linked.

It seems to me there could not be any error on my side.

**Comment by vnbaaij** [comment]
Try running it again from Visual Studio after removing the following part from web.config and let me know what error you get / if you still get an error. Stange thing is that for me it started working after I removed these lines.

```
<httpErrors errorMode="Custom" existingResponse="Replace">
      <remove statusCode="404" />
      <!-- Note! You should change this to your custom error page. See the
                 readme on https://github.com/Geta/404handler for more information -->
      <error statusCode="404" path="/notfound.aspx" responseMode="ExecuteURL" />
    </httpErrors>
```

**Comment by JiriCepelkaFirstLineSoftware** [comment]
> Try running it again from Visual Studio after removing the following part from web.config and let me …

I’ve already done this. You can check error on main post link _Exception page_. Changing these lines changes nothing except hiding the error from page. In event viewer the exception is still the same.

**Comment by vnbaaij** [comment]
Hmm, strange. Like I wrote, it works on my machine after fresh cloning and deleting those lines. I saw the error you posted, but it doesn't really help me in finding what the problem can be, I'm afraid. I'll take a closer look and let you know if/what I find

**Comment by JiriCepelkaFirstLineSoftware** [comment]
> Hmm, strange. Like I wrote, it works on my machine after fresh cloning and deleting those lines…

Ok, ok. Thanks. I’ll also continue investigation on this. I added also general event info but the info here don’t seem anyhow more useful.

**Comment by vnbaaij** [comment]
So it is working now?

**Comment by JiriCepelkaFirstLineSoftware** [comment]
I have to apologize. There was error in [Error List](http://uzivatel919.sweb.cz/Error.png). Since it was not resulting in build failure I did not attach importance to it.

Solution is to move project to shorter path since there is [no other solution](https://github.com/NuGet/Home/issues/3324).

**Comment by JiriCepelkaFirstLineSoftware** [comment]
> So it is working now?

I have to apologize. There was error in [Error List](http://uzivatel919.sweb.cz/Error.png). Since it was not resulting in build failure I did not attach importance to it.

Solution is to move project to shorter path since there is [no other solution](https://github.com/NuGet/Home/issues/3324).

**Comment by vnbaaij** [comment]
No problem. Glad you got it working.
