### ISSUE TITLE
What is default admin password

### ISSUE THREAD

**Issue by anjumrizwi** [episerver/AlloyDemoKit#8]
What is default admin password?

**Comment by anjumrizwi** [comment]
I got the password from release notes

Logins
• Admin user
o   U: epiadmin
o   P: ep!pass
• News editor
o   U: nancy
o   P: ep!pass
o   Notes: Limited access to News and Events area of site and Blocks/Media area, various top navigation menus removed, no ability to publish.
• Product editor
o   U: peter
o   P: ep!pass
o   Notes: Limited access to Product areas of site and Blocks/Media area, various top navigation menus removed, no ability to publish.

**Comment by jacobkhan** [comment]
You can also login with your machines admin account... Does Epiadmin not work?
